# Generated by Django 5.2.13 on 2026-06-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='temp_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
