# Generated by Django 5.2.13 on 2026-06-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
