# Generated by Django 5.2.13 on 2026-06-13 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_user',
            field=models.ForeignKey(blank=True, help_text='کاربری که پول از کیف پولش کم شد (null = سیستم/پلتفرم)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_user',
            field=models.ForeignKey(blank=True, help_text='کاربری که پول به کیف پولش اضافه شد (null = سیستم/پلتفرم)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
